### ISSUE TITLE
[Feature] CSS root theme settings

### ISSUE THREAD

**Issue by SpaceEnergy** [SteamClientHomebrew/Core#13]
### Before Requesting

- [X] I found no existing issue matching my feature request
- [X] This request is related to Millennium, and not a request for a specific theme/addon

### Describe the feature you'd like!

Root setting for themes:
```json
"css-root": "path/to/css/root"
```
e.g.
![image](https://github.com/user-attachments/assets/b075a228-314d-4a59-94dc-5fe6a6e5c486)

You add the css root path in the skin.json and Millennium looks in the root file for variables e.g. for colors `--accent: #352344;` or with rgb `--accent: 53, 35, 68;` or others like e.g. b `--margin-small: 6px;` and these variables are then displayed in the theme settings window in steam and you can edit them, if a different type of code is then set for the colors, it is converted to the type that was previously (default color code `hex` and the user specifies `rgb` it is converted to `hex` so that there are no problems with the theme)

Translated with www.DeepL.com/Translator

**Comment by ShadowMonster99** [comment]
Added the feature, see here for more:
https://docs.steambrew.app/developers/themes/theme-colors
