### ISSUE TITLE
[Bug] Updating any theme causes UI reload

### ISSUE THREAD

**Issue by ricewind012** [SteamClientHomebrew/Core#19]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is caused by the Millennium interface inside Steam (Themes, Plugins & Update Panel).
- [X] My issue is not caused by a theme

### Describe the Bug

no matter what theme is being used, updating causes the ui to be reloaded

### Expected Behavior

not reloading, or maybe prompt to do so

### Steps To Reproduce

1. In the "Updates" tab click on "Update"

### Operating System

Linux

**Comment by ShadowMonster99** [comment]
You're running steam with -dev, which hot reloads whenever files change inside the steamui folder.
